# Site settings
title: Blog of Jayn
SEOTitle: Jayn的博客 | Blog of Jayn
header-img: img/home-bg.jpg
email: jimyang1ss@sjtu.edu.cn
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://Jayn.com"
#twitter_username: SBootstrap
github_username:  JayYangSS
facebook_username:  jimyangboy
zhihu_username: xiao-ming-53-57
weibo_username: u/2122271063

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
gems: [jekyll-paginate]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 5001


# Duoshuo settings
duoshuo_username: Jayn
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing