# Site settings
title: Blog of Jayn
header-img: img/home-bg.jpg
email: jimyang1ss@sjtu.edu.cn
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://Jayn.com"
twitter_username: SBootstrap
github_username:  JayYangSS
facebook_username:  jimyangboy

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
gems: [jekyll-paginate]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 5001
